apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pi-prod

resources:
- ../common

patches:
- target:
    kind: Ingress
    name: hello-world-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: hello.local

images:
- name: ghcr.io/mk48/simple-http
  newTag: "3"
