apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hello-world-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: hello-world-secret
  data:
    - secretKey: DB_PASS
      remoteRef:
        key: mk/stage/db-pass
        property: password
