apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pi-stage

resources:
- ../common

patches:
- target:
    kind: Ingress
    name: hello-world-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: hello-stage.local
- target:
    kind: Deployment
    name: hello-world
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
- target:
    kind: Deployment
    name: hello-world
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/envFrom
      value:
        - configMapRef:
            name: hello-world-config

images:
- name: ghcr.io/mk48/simple-http
  newTag: "4"
