{{- range $i, $cluster := .Values.clusters }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-rest-api-{{ $cluster.name }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  # cleans up on delete
spec:
  project: default
  source:
    repoURL: https://github.com/mk48/k3s-infra
    targetRevision: main
    path: projects/simple-rest-api/overlay/{{ $cluster.name }}
  destination:
    server: https://kubernetes.default.svc
    namespace: pi-{{ $cluster.name }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}